image: gradle:alpine

variables:
  path: "/builds/$CI_PROJECT_PATH"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script:
    - gradle build
    - mv $path/build/libs/*.jar $path/
  artifacts:
    paths:
      - $path/*.jar
