name: EpicTimber
version: 0.0.1
author: Songoda
main: com.songoda.epictimber.EpicTimber
api-version: 1.13
commands:
  epictimber:
    description: Does something, probably
    usage: /epictimber
    aliases: [ep]