name: UltimateTimber
version: 0.0.1
author: Songoda
main: com.songoda.ultimatetimber.UltimateTimber
api-version: 1.13
commands:
  epictimber:
    description: Does something, probably
    usage: /ultimatetimber
    aliases: [ep]