name: UltimateTimber
version: maven-version-number
author: Songoda
main: com.songoda.ultimatetimber.UltimateTimber
api-version: 1.13
softdepend: [Multiverse-Core, mcMMO, Jobs]
commands:
  ultimatetimber:
    description: Reloads the configuration file
    usage: /ultimatetimber reload
    aliases: [ut]
permissions:
  ultimatetimber.*:
    description: Inherits all plugin permissions
    children:
      ultimatetimber.chop: true
      ultimatetimber.bonusloot: true
      ultimatetimber.reload: true
  ultimatetimber.chop:
    description: Allows players to trigger the trees toppling down effect
    default: op
  ultimatetimber.bonusloot:
    description: Doubles the loot obtained from trees
    default: op
  ultimatetimber.reload:
    description: Reloads the configuration file
    default: op